version: "3.8"

services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Add any other environment variables needed for your app
