import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";

import "../globals.css";
import { Providers } from "../providers";
import Sidebar from "../components/Sidebar";
import SidebarItems from "../components/SidebarItems";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <section className="bg-default-100 flex">
            <Sidebar>
              <SidebarItems />
            </Sidebar>
            <section className="flex-1 flex flex-col">
              {children} <Analytics />
            </section>
          </section>
        </Providers>
      </body>
    </html>
  );
}
